# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: arturo.olivares@stud.uni-due.de
author_name: Arturo Olivares Martos
has_ai_rules: false
has_binder: true
has_settings: false
kind: frontend
labextension_name: LAextension
project_short_description: A JupyterLab extension for the LA Course.
python_name: LAextension
repository: https://github.com/arturo-olvrs/LA-Jupyter-Extension.git
test: true

